var rand1 = Int.random(in: 1...70)
var rand2 = Int.random(in: 1...70)
var rand3 = Int.random(in: 1...70)
var rand4 = Int.random(in: 1...70)
var rand5 = Int.random(in: 1...70)

var power = Int.random(in: 1...30)
print("Your numbers are:")
print(rand1,rand2,rand3,rand4,rand5)
print("Your power number is:")
print(power)
